---

- hosts: brokernodes
  sudo: True
  roles:
    - { role: broker }

- hosts: logstashnodes
  sudo: True
  roles:
    - { role: logstash }

- hosts: searchnodes
  sudo: True
  roles:
    - { role: searchengine }
    - { role: kibana}

- hosts: shippernodes
  sudo: True
  roles:
    - { role: shipper }

