---

# Epel rpm url
url_epel_rpm: http://mirror.oss.ou.edu/epel/6/i386/epel-release-6-8.noarch.rpm

redis:
  deb:
    package: 'redis-server'
    service: 'redis-server'
  redhat:
    package: 'redis'
    service: 'redis'

redmon:
  service: 'redmon'
  deb:
    dependencies:
      - 'git'
      - 'ruby1.9.1'
      - 'ruby1.9.1-dev'      
      - 'g++'
      - 'make'
  redhat:
    dependencies:
      - 'git'
      - 'ruby'
      - 'gcc-c++'
      - 'make'
  gems:
    - 'bundler'
    - 'redmon'
  bin: '/usr/local/bin/redmon'
