---

- name: Install Apache and python-passlib
  yum: name={{ item }} state=installed
  with_items:
    - httpd
    - python-passlib
  notify:
    - restart apache

- name: Fetch Kibana source
  get_url: url={{ kibana_url }}{{ kibana_version }}.tar.gz dest=/tmp/{{ kibana_version }}.tar.gz

- name: Unarchive source to vhost
  command: tar -C {{ kibana_doc_root }}/html -zxf /tmp/{{ kibana_version }}.tar.gz

- name: Replace the URI of the ElasticSearch service in config.js on Kibana server
  lineinfile: >
    dest={{ kibana_doc_root }}html/{{ kibana_version }}/{{ kibana_config_file }}
    regexp='(elasticsearch.* \"http.*)$'
    state=present
    line='elasticsearch: "http://{{ elasticsearch_host }}:{{ elasticsearch_port }}", '
  notify:
   - restart apache
