---

- name: Ensure Elasticsearch signing key is installed
  rpm_key: key={{ url_es_gpg_key }}

- name: Ensure the repo file for ElasticSearch is ready
  copy: src=Elasticsearch-yum.repo dest=/etc/yum.repos.d/Elasticsearch_yum.repo owner=root group=root mode=0644

- name: Ensure openjdk and elasticsearch is installed
  yum: name={{ item }}
  with_items:
    - java-1.7.0-openjdk
    - elasticsearch

#- name: Ensure elasticsearch boots on startup
#  command: chkconfig elasticsearch on
#  notify:
#    - restart elasticsearch

- name: Ensure elasticsearch is running and boots on startup
  service: name=elasticsearch state=started enabled=yes
